# app/api/chat.py
import json
import time
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from langchain_core.messages import HumanMessage
from langgraph.checkpoint.redis import RedisSaver

from app.models.schemas import ChatRequest, ChatResponse
from app.services.agent import workflow, llm, build_rag_prompt
from app.core.config import REDIS_URL

router = APIRouter(prefix="/chat", tags=["Chat"])

@router.post("/stream")
async def chat_stream(request: ChatRequest):
    # Paste your existing chat_stream logic here
    """
    Server-Sent Events endpoint. Streams pipeline status updates 
    followed by token-by-token answer generation.
    
    SSE event types:
      {"status": "<node_name>"}  — pipeline progress
      {"status": "generating"}   — answer generation starting
      {"token": "<text>"}        — streamed answer token
      {"done": true, "citations": [...]} — stream complete
      {"error": "<message>"}     — error occurred
    """
    def generate():
        try:
            with RedisSaver.from_conn_string(REDIS_URL) as checkpointer:
                agent_app = workflow.compile(checkpointer=checkpointer)
                config = {"configurable": {"thread_id": request.thread_id}}
                
                # --- Phase 1: Run pipeline (router → expand → search → grade) ---
                pipeline_state = {}
                for update in agent_app.stream(
                    {"messages": [HumanMessage(content=request.message)]},
                    config=config,
                    stream_mode="updates"
                ):
                    node_name = list(update.keys())[0]
                    if node_name == "__end__":
                        continue
                    node_data = list(update.values())[0]
                    pipeline_state.update(node_data)
                    yield f"data: {json.dumps({'status': node_name})}\n\n"
                
                context = pipeline_state.get("context", "chitchat")
                yield f"data: {json.dumps({'status': 'generating'})}\n\n"
                
                # --- Phase 2: Stream the answer token-by-token ---
                if context == "vectorstore":
                    docs = pipeline_state.get("filtered_docs", [])
                    
                    if not docs:
                        yield f"data: {json.dumps({'token': 'Maaf, tidak ada informasi relevan di dalam dokumen yang diunggah.'})}\n\n"
                        yield f"data: {json.dumps({'done': True, 'citations': []})}\n\n"
                        return
                    
                    prompt = build_rag_prompt(docs, request.message)
                    for chunk in llm.stream([HumanMessage(content=prompt)]):
                        if chunk.content:
                            yield f"data: {json.dumps({'token': chunk.content})}\n\n"
                    
                    citations = []
                    for d in docs:
                        citations.append({
                            "filename": d.metadata.get("filename", ""),
                            "source_type": d.metadata.get("source_type", ""),
                            "file_url": d.metadata.get("file_url", ""),
                        })
                    yield f"data: {json.dumps({'done': True, 'citations': citations})}\n\n"
                
                elif context == "summarize":
                    # [THE FIX] Extract the answer already generated by fetch_summary_node
                    messages = pipeline_state.get("messages", [])
                    if messages:
                        final_text = messages[-1].content
                        # Simulate streaming so the UI still looks nice
                        for word in final_text.split(" "):
                            yield f"data: {json.dumps({'token': word + ' '})}\n\n"
                            time.sleep(0.01) # Optional: slight delay for smooth typing effect
                    else:
                        yield f"data: {json.dumps({'token': 'Gagal mengambil ringkasan.'})}\n\n"
                    
                    yield f"data: {json.dumps({'done': True, 'citations': []})}\n\n"

                else:
                    # Chitchat — stream directly
                    for chunk in llm.stream([HumanMessage(content=request.message)]):
                        if chunk.content:
                            yield f"data: {json.dumps({'token': chunk.content})}\n\n"
                    yield f"data: {json.dumps({'done': True, 'citations': []})}\n\n"
                    
        except Exception as e:
            import traceback
            traceback.print_exc()
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
    
    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}
    )

@router.post("", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    # Paste your existing chat_endpoint logic here
    try:
        with RedisSaver.from_conn_string(REDIS_URL) as checkpointer:
            agent_app = workflow.compile(checkpointer=checkpointer)
            config = {"configurable": {"thread_id": request.thread_id}}
            
            result = agent_app.invoke(
                {"messages": [HumanMessage(content=request.message)]},
                config=config
            )
            
            context = result.get("context", "chitchat")
            
            if context == "vectorstore":
                docs = result.get("filtered_docs", [])
                if not docs:
                    return {"response": "Maaf, tidak ada informasi relevan di dalam dokumen yang diunggah.", "citations": []}
                
                prompt = build_rag_prompt(docs, request.message)
                response = llm.invoke([HumanMessage(content=prompt)])
                
                citations = [
                    {"filename": d.metadata.get("filename", ""), "source_type": d.metadata.get("source_type", "")}
                    for d in docs
                ]
                return {"response": response.content, "citations": citations}
            elif context == "summarize":
                # [THE FIX] Grab the last message generated by the graph
                messages = result.get("messages", [])
                final_text = messages[-1].content if messages else "Gagal mengambil ringkasan."
                return {"response": final_text, "citations": []}
            else:
                response = llm.invoke([HumanMessage(content=request.message)])
                return {"response": response.content, "citations": []}

    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))