import os
import json
import shutil
import time
from typing import Optional, List, Any

# FastAPI Imports
from fastapi import FastAPI, UploadFile, File, Depends, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from sqlalchemy.orm import Session

# DB Imports
from db.postgres import get_db
from db.minio_client import minio_client, bucket_name
from db.redis_client import redis_client

# AI Imports
from app.ingest_service import ingest_file
from app.agent import workflow, REDIS_URL, llm, build_rag_prompt
from langgraph.checkpoint.redis import RedisSaver
from langchain_core.messages import HumanMessage

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------
# DATA MODELS
# ---------------------------------------------------------
class ChatRequest(BaseModel):
    message: str
    thread_id: str = "default_thread"

class ChatResponse(BaseModel):
    response: str
    citations: List[Any] = []

# ---------------------------------------------------------
# STARTUP EVENT
# ---------------------------------------------------------
@app.on_event("startup")
def startup_event():
    try:
        print("⚙️ Startup: Verifying Redis Indices...")
        with RedisSaver.from_conn_string(REDIS_URL) as checkpointer:
            checkpointer.setup()
        print("✅ Redis Indices Ready.")
    except Exception as e:
        print(f"⚠️ Redis Setup Note: {e}")

# ---------------------------------------------------------
# STREAMING CHAT ENDPOINT (SSE)
# ---------------------------------------------------------
@app.post("/chat/stream")
async def chat_stream(request: ChatRequest):
    """
    Server-Sent Events endpoint. Streams pipeline status updates 
    followed by token-by-token answer generation.
    
    SSE event types:
      {"status": "<node_name>"}  — pipeline progress
      {"status": "generating"}   — answer generation starting
      {"token": "<text>"}        — streamed answer token
      {"done": true, "citations": [...]} — stream complete
      {"error": "<message>"}     — error occurred
    """
    def generate():
        try:
            with RedisSaver.from_conn_string(REDIS_URL) as checkpointer:
                agent_app = workflow.compile(checkpointer=checkpointer)
                config = {"configurable": {"thread_id": request.thread_id}}
                
                # --- Phase 1: Run pipeline (router → expand → search → grade) ---
                pipeline_state = {}
                for update in agent_app.stream(
                    {"messages": [HumanMessage(content=request.message)]},
                    config=config,
                    stream_mode="updates"
                ):
                    node_name = list(update.keys())[0]
                    if node_name == "__end__":
                        continue
                    node_data = list(update.values())[0]
                    pipeline_state.update(node_data)
                    yield f"data: {json.dumps({'status': node_name})}\n\n"
                
                context = pipeline_state.get("context", "chitchat")
                yield f"data: {json.dumps({'status': 'generating'})}\n\n"
                
                # --- Phase 2: Stream the answer token-by-token ---
                if context == "vectorstore":
                    docs = pipeline_state.get("filtered_docs", [])
                    
                    if not docs:
                        yield f"data: {json.dumps({'token': 'Maaf, tidak ada informasi relevan di dalam dokumen yang diunggah.'})}\n\n"
                        yield f"data: {json.dumps({'done': True, 'citations': []})}\n\n"
                        return
                    
                    prompt = build_rag_prompt(docs, request.message)
                    for chunk in llm.stream([HumanMessage(content=prompt)]):
                        if chunk.content:
                            yield f"data: {json.dumps({'token': chunk.content})}\n\n"
                    
                    citations = []
                    for d in docs:
                        citations.append({
                            "filename": d.metadata.get("filename", ""),
                            "source_type": d.metadata.get("source_type", ""),
                            "file_url": d.metadata.get("file_url", ""),
                        })
                    yield f"data: {json.dumps({'done': True, 'citations': citations})}\n\n"
                
                elif context == "summarize":
                    # [THE FIX] Extract the answer already generated by fetch_summary_node
                    messages = pipeline_state.get("messages", [])
                    if messages:
                        final_text = messages[-1].content
                        # Simulate streaming so the UI still looks nice
                        for word in final_text.split(" "):
                            yield f"data: {json.dumps({'token': word + ' '})}\n\n"
                            time.sleep(0.01) # Optional: slight delay for smooth typing effect
                    else:
                        yield f"data: {json.dumps({'token': 'Gagal mengambil ringkasan.'})}\n\n"
                    
                    yield f"data: {json.dumps({'done': True, 'citations': []})}\n\n"

                else:
                    # Chitchat — stream directly
                    for chunk in llm.stream([HumanMessage(content=request.message)]):
                        if chunk.content:
                            yield f"data: {json.dumps({'token': chunk.content})}\n\n"
                    yield f"data: {json.dumps({'done': True, 'citations': []})}\n\n"
                    
        except Exception as e:
            import traceback
            traceback.print_exc()
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
    
    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"}
    )

# ---------------------------------------------------------
# NON-STREAMING CHAT ENDPOINT (kept for backwards compat)
# ---------------------------------------------------------
@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(request: ChatRequest):
    try:
        with RedisSaver.from_conn_string(REDIS_URL) as checkpointer:
            agent_app = workflow.compile(checkpointer=checkpointer)
            config = {"configurable": {"thread_id": request.thread_id}}
            
            result = agent_app.invoke(
                {"messages": [HumanMessage(content=request.message)]},
                config=config
            )
            
            context = result.get("context", "chitchat")
            
            if context == "vectorstore":
                docs = result.get("filtered_docs", [])
                if not docs:
                    return {"response": "Maaf, tidak ada informasi relevan di dalam dokumen yang diunggah.", "citations": []}
                
                prompt = build_rag_prompt(docs, request.message)
                response = llm.invoke([HumanMessage(content=prompt)])
                
                citations = [
                    {"filename": d.metadata.get("filename", ""), "source_type": d.metadata.get("source_type", "")}
                    for d in docs
                ]
                return {"response": response.content, "citations": citations}
            elif context == "summarize":
                # [THE FIX] Grab the last message generated by the graph
                messages = result.get("messages", [])
                final_text = messages[-1].content if messages else "Gagal mengambil ringkasan."
                return {"response": final_text, "citations": []}
            else:
                response = llm.invoke([HumanMessage(content=request.message)])
                return {"response": response.content, "citations": []}

    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))
    

@app.post("/upload/")
async def upload_file(
    background_tasks: BackgroundTasks, 
    file: UploadFile = File(...), 
    db: Session = Depends(get_db)
):
    """
    Uploads file to MinIO and triggers AI Ingestion in background.
    """
    try:
        # 1. Save to MinIO
        file_content = await file.read()
        file_size = len(file_content)
        
        # Reset cursor before reading again or saving
        await file.seek(0)
        
        minio_client.put_object(
            bucket_name,
            file.filename,
            file.file, 
            length=file_size,
            content_type=file.content_type
        )
        
        # 2. Save to Temp File for Ingestion Service
        temp_dir = "temp_uploads"
        os.makedirs(temp_dir, exist_ok=True)
        temp_path = os.path.join(temp_dir, file.filename)
        
        with open(temp_path, "wb") as f:
            f.write(file_content)

        # 3. Trigger Background Task
        # The API responds immediately, Python works in background
        background_tasks.add_task(process_ingestion, temp_path, file.filename)

        return {
            "status": "success", 
            "message": "File uploaded. AI processing started.",
            "filename": file.filename
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Helper function for background task
def process_ingestion(file_path: str, filename: str):
    print(f"🔄 Background: Starting ingestion for {filename}...")
    try:
        # Call your existing ingestion logic
        ingest_file(file_path) 
        print(f"✅ Background: Ingestion complete for {filename}")
    except Exception as e:
        print(f"❌ Background Ingestion failed: {e}")
    finally:
        # Cleanup temp file
        if os.path.exists(file_path):
            os.remove(file_path)

@app.get("/files/")
async def list_files():
    try:
        if not minio_client.bucket_exists(bucket_name):
            return {"files": []}
        objects = minio_client.list_objects(bucket_name, recursive=True)
        return {"files": [{"name": o.object_name, "size": o.size} for o in objects]}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/health")
async def health_check():
    return {"status": "online", "service": "FastAPI Agent"}

if __name__ == "__main__":
    import uvicorn
    # 0.0.0.0 allows external access (required for connecting from other machines)
    uvicorn.run(app, host="0.0.0.0", port=8000)